# Generated by Django 5.0 on 2023-12-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('codigo_produto', models.IntegerField()),
                ('descricao_produto', models.TextField()),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
